name: Run Steampipe Checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  steampipe-terraform-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Steampipe terraform scan action - with mod & default check all
        continue-on-error: true
        uses: turbot/steampipe-action/tfscan@release/v0.1
        with:
          directory: examples/terraform/aws/
          mod: https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git

      # - name: Steampipe terraform scan action - with mod and specific controls
      #   continue-on-error: true
      #   uses: turbot/steampipe-action/tfscan@tfscan
      #   with:
      #     mod: https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git
      #     run: control.ec2_instance_not_use_default_vpc control.ec2_ebs_default_encryption_enabled control.s3_bucket_default_encryption_enabled
