name: Run Steampipe Checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  steampipe-terraform-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Steampipe terraform scan action
        continue-on-error: true
        uses: ./
        with:
          connection_config: |
            connection "terraform" {
              plugin = "terraform"
              paths = ["examples/terraform/aws/**/*.tf"]
            }
          plugins: terraform
          mod: 'https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git'
          run: control.ec2_instance_not_use_default_vpc,control.ec2_ebs_default_encryption_enabled
