name: Run Steampipe Checks
on:
  push:
    branches:
      - action-kp-lt
  pull_request:

jobs:
  steampipe-terraform-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      # - uses: nbaztec/add-pr-review-comment@v1
      #   with:
      #     comments: |
      #       [{"path":"index.ts","line":10,"text":"something was deleted","side":"RIGHT"},{"path":"index.ts","line":8,"text":"something was added","side":"LEFT"}]
      #     repo-token: ${{ github.token }}
      #     repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub tokens
      #     allow-repeats: false # This is the default
      - name: Steampipe terraform scan action
        continue-on-error: false
        uses: ./
        with:
          version: "latest"
          connection_config: |
            connection "terraform" {
              plugin = "terraform"
              paths = ["examples/terraform/aws/**/*.tf"]
            }
          plugins: terraform
          mod: "https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git"
          run: control.ec2_instance_not_use_default_vpc,control.ec2_ebs_default_encryption_enabled,control.s3_bucket_default_encryption_enabled
