# 1. Set up secrets in your workspace:
#   - TF_PATH with the path to the directory having the terraform files

name: Test workflow
on:
  push:
    branches:
      - first-setup
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local my-action
        uses: ./
        with:
          version: 'latest'
          connection_config: |
            connection "terraform" {
              plugin = "terraform"
              paths = ${{ secrets.TF_PATH }}
            }
          plugins: "[\"terraform\"]"
          mod: 'https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git'
          command: steampipe check all
