name: Run Steampipe Action
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Run local Action
        uses: ./
        with:
          connection_config: |
            connection "terraform" {
              plugin = "terraform"
              paths = ${{ secrets.TF_PATH }}
            }
          plugins: terraform
          mod: "https://github.com/turbot/steampipe-mod-terraform-aws-compliance.git"
          export: export.json
          run: control.ec2_ebs_default_encryption_enabled
