name: Test workflow Lalit
on:
  push:
    branches:
      - first-setup-lalit
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Use local my-action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          version: "latest"
          connection_config: |
            connection "github" {
              plugin = "github"
              # paths = [ "" ]
            }
          plugins: |
            ["github"]
          # mod: "https://github.com/turbot/steampipe-utils.git"
          mod: "."
