name: tfsec-pr-commenter
on:
  push:
    branches:
      - fix-tfsec-workflow
  pull_request:

jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        # uses: aquasecurity/tfsec-pr-commenter-action@main
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: "test_dir"
          tfsec_args: --soft-fail
        #  github_token: ${{ secrets.GH_TOKEN }}
